### ISSUE TITLE
Password does not match for user "root"

### ISSUE THREAD

**Issue by niccololampa** [voxpelli/node-pg-pubsub#80]
I am trying to connect my postgres via my websocket and my postgres database logs the 

```
password does not match for user "root".
sample-db |  Connection matched pg_hba.conf line 95: "host all all all md5"
```

My postgres setup is the following:

```
 image: postgres:11.2-alpine
    container_name: sample-db
    ports:
      - 5432:5432      
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
```

How do I properly write the syntax for 
`var pubsubInstance = new PGPubsub('postgres://username@localhost/database') `
using the postgres credentials above ?

Currenly this is how I wrote it

`pubsubInstance = new PGPubsub('postgres://root@localhost:5432/sample_db');`
